spring.application.name=Bank_Project
spring.datasource.url=jdbc:postgresql://localhost:5432/evision
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=9090